language: node_js
node_js:
  - "20"
  - "18"

before_install:
  - corepack enable
  - corepack prepare pnpm@latest --activate

install:
  - pnpm install --frozen-lockfile

cache:
  directories:
    - "$HOME/.local/share/pnpm/store"
