// @flow

export type HolidayType =
  | 'NEUJAHRSTAG'
  | 'HEILIGEDREIKOENIGE'
  | 'KARFREITAG'
  | 'OSTERSONNTAG'
  | 'OSTERMONTAG'
  | 'TAG_DER_ARBEIT'
  | 'CHRISTIHIMMELFAHRT'
  | 'MARIAHIMMELFAHRT'
  | 'PFINGSTSONNTAG'
  | 'PFINGSTMONTAG'
  | 'FRONLEICHNAM'
  | 'DEUTSCHEEINHEIT'
  | 'REFORMATIONSTAG'
  | 'ALLERHEILIGEN'
  | 'BUBETAG'
  | 'ERSTERWEIHNACHTSFEIERTAG'
  | 'ZWEITERWEIHNACHTSFEIERTAG';

export const allHolidays: Array<HolidayType> = [
  'NEUJAHRSTAG',
  'HEILIGEDREIKOENIGE',
  'KARFREITAG',
  'OSTERSONNTAG',
  'OSTERMONTAG',
  'TAG_DER_ARBEIT',
  'CHRISTIHIMMELFAHRT',
  'MARIAHIMMELFAHRT',
  'PFINGSTSONNTAG',
  'PFINGSTMONTAG',
  'FRONLEICHNAM',
  'DEUTSCHEEINHEIT',
  'REFORMATIONSTAG',
  'ALLERHEILIGEN',
  'BUBETAG',
  'ERSTERWEIHNACHTSFEIERTAG',
  'ZWEITERWEIHNACHTSFEIERTAG',
];
